import { writeFileSync } from "fs"
import { ExecArgs } from "@medusajs/framework/types"
import {
  ContainerRegistrationKeys,
  Modules,
} from "@medusajs/framework/utils"
import {
  createApiKeysWorkflow,
  linkSalesChannelsToApiKeyWorkflow,
} from "@medusajs/medusa/core-flows"

/**
 * Creates a fresh publishable API key linked to the default sales channel.
 * If STOREFRONT_ENV_PATH is set, writes a Next.js .env.local file there.
 * Always prints the token alone on the last stdout line for shell capture.
 */
export default async function exportPublishableKey({ container }: ExecArgs) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)
  const storeModule = container.resolve(Modules.STORE)
  const [store] = await storeModule.listStores({}, { take: 1 })

  if (!store?.default_sales_channel_id) {
    throw new Error("No default sales channel on store — run seed first.")
  }

  const {
    result: [apiKey],
  } = await createApiKeysWorkflow(container).run({
    input: {
      api_keys: [
        {
          title: `Cryptonly storefront ${new Date().toISOString()}`,
          type: "publishable",
          created_by: "",
        },
      ],
    },
  })

  await linkSalesChannelsToApiKeyWorkflow(container).run({
    input: {
      id: apiKey.id,
      add: [store.default_sales_channel_id],
    },
  })

  const token = (apiKey as { token?: string }).token
  if (!token) {
    throw new Error("createApiKeysWorkflow did not return a token")
  }

  const envPath = process.env.STOREFRONT_ENV_PATH
  if (envPath) {
    const backendUrl =
      process.env.STOREFRONT_BACKEND_URL || "http://localhost:9000"
    const contents = [
      "# Generated by export-publishable-key.ts — do not commit",
      `MEDUSA_BACKEND_URL=${backendUrl}`,
      `NEXT_PUBLIC_MEDUSA_BACKEND_URL=${backendUrl}`,
      `NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${token}`,
      "NEXT_PUBLIC_BASE_URL=http://localhost:8000",
      "NEXT_PUBLIC_DEFAULT_REGION=dk",
      "REVALIDATE_SECRET=supersecret",
      "",
    ].join("\n")
    writeFileSync(envPath, contents, "utf8")
    logger.info(`Wrote storefront env to ${envPath}`)
  }

  logger.info(`Created publishable API key ${apiKey.id}`)
  // Last line of stdout for optional shell capture (prefer STOREFRONT_ENV_PATH)
  process.stdout.write(`${token}\n`)
}
